# .github/project-roadmap.yml
# Declarative config for the Stacklion professional-class roadmap.

project:
  owner: "MadeinPh1la"          # GitHub user or org that owns the project
  owner_type: "USER"            # "USER" or "ORGANIZATION"
  name: "@MadeinPh1la's Stacklion API"
  # No project_number: script will find or create by name.

repository:
  full_name: "MadeinPh1la/stacklion-api"

phases:
  - code: "E9"
    milestone: "E9 – Persistent Data Quality & Fact Store"
    label: "phase:E9"
    default_status: "Backlog"

  - code: "E10"
    milestone: "E10 – XBRL Normalization Layer"
    label: "phase:E10"
    default_status: "Backlog"

  - code: "E11"
    milestone: "E11 – Reconciliation Engine"
    label: "phase:E11"
    default_status: "Backlog"

  - code: "E12"
    milestone: "E12 – Auditability & Provenance"
    label: "phase:E12"
    default_status: "Backlog"

  - code: "E13"
    milestone: "E13 – Modeling Warehouse Layer"
    label: "phase:E13"
    default_status: "Backlog"

  - code: "E14"
    milestone: "E14 – Professional Modeling APIs"
    label: "phase:E14"
    default_status: "Backlog"

  - code: "E15"
    milestone: "E15 – MCP Modeling Capabilities"
    label: "phase:E15"
    default_status: "Backlog"

  - code: "E16"
    milestone: "E16 – Reliability, SLOs, and Scaling"
    label: "phase:E16"
    default_status: "Backlog"

  - code: "E17"
    milestone: "E17 – AI and Advanced Modeling Enhancements"
    label: "phase:E17"
    default_status: "Backlog"

views:
  # Roadmap table grouped by milestone (configure manually in Project UI).
  - name: "Roadmap"
    layout: "TABLE"
    filter: "is:issue repo:MadeinPh1la/stacklion-api"
    group_by_field: "Milestone"

  # Delivery Kanban for near-term work (E9 + E10).
  - name: "Delivery board"
    layout: "BOARD"
    filter: "is:issue repo:MadeinPh1la/stacklion-api label:phase:E9,label:phase:E10"
    group_by_field: "Status"

# Project Status field configuration.
# Create a Project field named "Status" (single-select) with options:
#   Backlog, In Progress, Blocked, Done
status_field:
  name: "Status"
  states:
    backlog: "Todo"          # <-- underlying option name
    in_progress: "In Progress"
    blocked: "Todo"          # or add a real "Blocked" option in the Project later
    done: "Done"

status_mapping:
  default_state: "Todo"
  in_progress_state: "In Progress"
  done_state: "Done"

  in_progress_labels:
    - "status:in_progress"

  done_labels:
    - "status:done"
